from enum import Enum


class ResponseCodes(Enum):
    SCHEMA_ONBOARDED = "TS_001"
    QUERY_GENERATED = "TS_002"
    SCHEMA_RETRIEVED = "TS_003"
    SCHEMA_NOT_FOUND = "TS_004"
    SCHEMA_ID_NOT_PROVIDED = "TS_005"
    CHATGPT_ERROR = "TE_001"
    SCHEMA_LOAD_ERROR = "TE_002"
    INSERT_PROMPT_ERROR = "TE_003"
    CREATE_DB_ERROR = "TE_004"

